# Site settings
title:          Core-Research-Team
description:    "RAON Whitehat Core-Research-Team Blog"
#baseurl:        "/tale"
baseurl:        ""
url:            "https://core-research-team.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Core-Research-Team
  url:          https://core-research-team.github.io
  email:        core-research-team@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-toc
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       99999

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale

toc:
    min_level: 1
    max_level: 2


host : 172.26.12.255
#host: 202.182.127.225
port: 4000
